import type { PublicDoc } from './types';

export const publicDocs: PublicDoc[] = [
    {
        id: 'A Type of Social Mechanics: A First-Principles Formal Framework for Systemic Stress, Normalization Traps, and Social Phase Transitions',
        titles: {
            CN: "一种社会力学：针对系统性压力、归一化陷阱与社会相变的第一性原理形式化框架",
            EN: "A Type of Social Mechanics: A First-Principles Formal Framework for Systemic Stress, Normalization Traps, and Social Phase Transitions",
            JA: "社会力学の一種：システム的ストレス、規格化の罠、および社会的相転移のための第一原理に基づく形式的フレームワーク"
        },
        date: '2026.02.28',
        descriptions: {
            CN: "现代社会正面临着以生育率骤降、普遍职业倦怠和深刻社会原子化为特征的结构性危机。然而，当代社会科学在微观个体决策与宏观系统性崩溃之间仍缺乏统一的物理框架。本文提出了“社会力学（Social Mechanics）”理论框架，将人类集体建模为受网络拓扑和热力学定律约束的非平衡动力系统。我们首先形式化了社会运动学中的“归一化陷阱（Normalization Trap）”：在由局部信息网络放大的评估指标压力下，受限于生理极限的个体相对位移不可避免地趋于零。这种加速度失配产生了一种非对称的“社会热机”，将有用功沿权力梯度激进提取，并将摩擦产生的系统废热向下耗散至边缘节点。模型表明，当累积压力突破个体承载阈值时，代理将启动“主动拓扑剪枝（Topological Pruning）”作为物理自我保护机制。一旦这种剪枝超过临界点，将引发压力向存活节点的急剧转移，最终导致社会网络内不可逆的相变和连锁雪崩。",
            EN: "Modern societies globally are confronting structural crises characterized by plummeting fertility rates, widespread occupational burnout, and profound social atomization. However, contemporary social sciences, while having developed extensive quantitative models for isolated phenomena, still lack a unified quantitative physical framework capable of bridging micro-level individual decisionmaking with macro-level systemic collapse. This paper proposes the theoretical framework of Social Mechanics, modeling human collectives as non-equilibrium dynamical systems constrained by network topology and thermodynamic laws. We first formalize the Normalization Trap of Social Kinematics: Under an exponentially expanding systemic evaluation metric (L max) amplified by local information networks, the relative social displacement of individuals (d ′ i)bounded by biological limits of absolute work capacity (C bio)-inevitably converges to zero. This acceleration mismatch, immersed in exceptionally high effective systemic damping (η eff), engenders an asymmetric Social Heat Engine. Useful work is aggressively extracted bidirectionally along power gradients and familial bonds, while the environmental stress (systemic waste heat) generated by internal friction is forcibly dissipated downward to marginal nodes. Our model demonstrates that when the accumulated total nodal stress inevitably breaches an individual's intrinsic carrying capacity threshold (τ i), the microagent will initiate active Topological Pruning as a mechanism of physical selfpreservation. We indicate that once such node-level pruning surpasses the critical tipping point (t crit) of the systemic stress capacity (C sys), it triggers an acute transfer of stress to surviving nodes, ultimately resulting in an irreversible phase transition and cascading avalanche within goal-directed social networks. This framework may offer preliminary quantitative indicators relevant to the systemic stress of complex human organizations.",
            JA: "現代社会は、出生率の急落、広範な燃え尽き症候群、そして深刻な社会的原子化といった構造的危機に直面しています。しかし、社会科学においては、ミクロレベルの意思決定とマクロレベルのシステム崩壊を橋渡しする統一的な物理学的フレームワークが依然として欠如しています。本論文では、人間集団をネットワークトポロジーと熱力学の法則に基づく非平衡力学系としてモデル化する「社会力学（Social Mechanics）」の理論的フレームワークを提案します。まず、社会的キネマティクスにおける「規格化の罠（Normalization Trap）」を定式化し、拡大する評価指標と生物学的限界の乖離によって個人の相対的な社会的変位がゼロに収束する仕組みを解明します。この加速度のミスマッチは、非対称な「社会的熱機関」を生み出し、有用な仕事を権力勾配に沿って抽出する一方、内部摩擦による「排熱（システムストレス）」を周辺ノードへと強制的に散逸させます。本モデルは、累計ストレスが個人の許容閾値を超えた際、自己保存メカニメントとして「能動的トポロジー剪定（Topological Pruning）」が開始されることを示しています。この剪定が臨界点を超えると生存ノードへのストレス急転を誘発し、組織内での不可逆的な相転移と連鎖的な崩壊を引き起こします。"
        },
        category: 'Paper',
        paperType: 'Full Paper',
        originalLangs: { CN: "英文", EN: "English", JA: "英語" },
        lengths: { CN: "66页", EN: "66 Pages", JA: "66ページ" },
        isInternal: false,
        journal: 'NHB (Desk Review)',
        publisher: 'Nature',
        impactFactor: '0',
        preprintUrl: '',
        externalUrl: ''
    },
    {
        id: 'large-scale-automated-auditing-of-user-feedback-in-games',
        titles: {
            CN: "大规模游戏用户反馈的自动审计：一种面向生产部署的资源高效本体导向框架",
            EN: "Large-Scale Automated Auditing of User Feedback in Games: A Resource-Efficient Ontology-Guided Framework for Production Deployment",
            JA: "ゲームにおけるユーザーフィードバックの大規模自動監査：プロダクション導入に向けたリソース効率の高いオントロジー誘導型フレームワーク"
        },
        date: '2026.02.19',
        descriptions: {
            CN: "游戏开发者在处理大规模用户反馈以识别可落地的设计弱点时，面临着关键的运营瓶颈。手动专家分析成本高昂（每小时 25-100 美元），而现有的情感分析工具缺乏诊断审计所需的结构化粒度。本文提出了一种资源高效的本体导向专家系统，通过零样本推理，仅利用提示工程（无需模型微调或带标注的训练数据），自动将玩家反馈解码为经过验证的 28 维设计分类法。我们在单台消费级 GPU（RTX 4080 笔记本）上，用约 40 小时处理了涵盖 887 个条目的 N = 14,574 条 Steam 评论。跨三种不同模型的架构验证得出的平均 PABAK = 0.82，表明模型间具有高度一致性。该系统实现了 96.8% 的覆盖率，单条评论的平均边际成本低于 0.0002 美元，仅为人工专家编码成本的不到千分之一。该框架将用户评论分析从周期性的手动审计转化为持续的自动化运营智能，为资源受限和中小规模的开发者普及了先进的设计分析能力。",
            EN: "Game developers face critical operational bottlenecks in processing large-scale user feedback to identify actionable design weaknesses. Manual expert analysis is prohibitively expensive ($25.00 ∼ 100.00 per hour), while existing sentiment analysis tools lack the structural granularity required for diagnostic auditing. This paper presents a resource-efficient ontology-guided expert system that automatically decodes player feedback into a validated 28-dimensional design taxonomy via zero-shot inference-requiring only prompt engineering, without model fine-tuning or annotated training data. We processed N = 14, 574 Steam reviews spanning 887 titles using Qwen-2.5-7B on a single consumer GPU (RTX 4080 Laptop) in approximately 40 hours. Multi-architecture validation across three diverse models yielded a mean PABAK = 0.82, indicating high inter-model consistency. The system achieved 96.8% coverage at an average marginal cost below $0.0002 per review-representing an analysis cost below 1/1,000th of manual expert coding. Comprehensive validation through multi-evidence triangulation establishes robustness: bootstrap PCA stability [1] (24 of 28 components for 90% variance), permutation-tested correlations (p < 0.001), and low multicollinearity (mean VIF = 1.08). Comparative baselines confirm substantial advantages over BERT zero-shot and S-BERT clustering. This framework transforms user review analysis from periodic manual audits into continuous, automated operational intelligence-democratizing advanced design analytics for resource-constrained developers. ",
            JA: "ゲーム開発者は、実行可能な設計上の弱点を特定するために、大規模なユーザーフィードバックを処理する際、運用上のボトルネックに直面しています。専門家による手動分析は非常に高コストであり、既存の感情分析ツールは診断監査に必要な構造的な粒度を欠いています。本論文では、モデルの微調整や教師データを必要とせず、プロンプトエンジニアリングのみを用いるゼロショット推論を介して、プレイヤーのフィードバックを検証済みの28次元設計分類法（タクソノミー）に自動的にデコードする、リソース効率の高いオントロジー誘導型エキスパートシステムを提案します。N = 14,574のSteamレビュー（887タイトル）を、単一の一般向けGPUを使用して約40時間で処理しました。検証の結果、高いモデル間一貫性（平均PABAK = 0.82）と96.8%の網羅率を達成し、レビューあたりの分析コストを手動分析の1/1,000以下に抑制することに成功しました。本フレームワークは、ユーザーレビュー分析を定期的な手動監査から継続的な自動分析へと変革し、リソースの限られた開発者にも高度なデザイン・アナリティクスを提供することを可能にします。"
        },
        category: 'Paper',
        paperType: 'Full Paper',
        originalLangs: { CN: "英文", EN: "English", JA: "英語" },
        lengths: { CN: "28页", EN: "28 Pages", JA: "28ページ" },
        isInternal: false,
        journal: 'ESWA (Desk Review)',
        publisher: 'Elsevier',
        impactFactor: '0',
        preprintUrl: 'https://doi.org/10.36227/techrxiv.177205021.16204089/v1',
        externalUrl: ''
    },
    {
        id: 'design-theoretic-taxonomy-for-participatory-systems',
        titles: {
            CN: "参与式系统的设计理论分类法：正交性、极简完备性与双层诊断架构",
            EN: "A Design-Theoretic Taxonomy for Participatory Systems: Orthogonality, Minimal Completeness, and the Dual-Layer Diagnostic Architecture",
            JA: "参加型システムのためのデザイン理論的タクソノミー：直交性、最小完備性、および二層診断アーキテクチャ"
        },
        date: '2026.02.14',
        descriptions: {
            CN: "交互系统中的人类参与通常通过系统级的设计特征或潜在的心理状态来分析，这在客观机制与主观体验之间创造了某种解释鸿沟。我们开发了一种设计理论分类法，通过双层诊断架构来弥合这一鸿沟：将客观系统属性（信号源）与主体感知（解码器）分离。我们建立了一个七维正交向量空间，将参与倾向分解为：产出收益、成本、时间投入、外在/内在动机、失败成本和风险结构。通过对 N = 14,717 条玩家评论的大规模实证验证，我们证明了三个基本属性：正交性、极简完备性（28 个分量中的 24 个可捕获 90% 方差）以及行为效度（96.08% 覆盖率）。这些结果表明，通过双层架构，参与可以作为一种结构上可审计的行为产物进行诊断。",
            EN: "Human participation in interactive systems is typically analyzed through either system-level design features or latent psychological states, creating an explanatory gap between objective mechanics and subjective experience. We develop a design-theoretic taxonomy that bridges this gap through a dual-layer diagnostic architecture: separating objective system properties (Signal Source) from agent perception (Decoder). We establish a seven-dimensional orthogonal vector space decomposing participatory propensity into: Output, Cost, Temporal Commitment, Extrinsic/Intrinsic Motivation, Failure Cost, and Risk Structure. Through largescale empirical validation on 𝑁 = 14,717 player reviews, we demonstrate three fundamental properties: (1) Orthogonality-dimensions exhibit weak correlation (modal |𝜌 | < 0.1) and function as independent design levers; (2) Minimal Completeness-24 of 28 components required for 90% variance capture, with each dimension explaining unique behavioral variance; (3) Behavioral Validity-96.08% coverage of substantive feedback, with systematic identification of residual categories falling outside structural design scope. We establish two critical theoretical advances: (1) The Structural Asymmetry of Failure-demonstrating that engagement success follows conjunctive logic (all dimensions must satisfy thresholds) while failure follows disjunctive logic (any single dimension violation triggers churn), explaining the systematic differences in user feedback complexity and correlation patterns; (2) Recursive Structural Applicability-evidence that the taxonomy applies recursively across micro (action), meso (session), and macro (lifecycle) granularities, validating cross-domain transferability beyond gaming to education, workplace, and civic systems. The taxonomy exhibits strong structural properties: low inter-dimensional correlation, linear PCA variance decay indicating genuine high-dimensionality, and empirical necessity of rare dimensions. These results establish that engagement can be treated as a structurally auditable behavioral product, with the dual-layer architecture enabling precise diagnosis of whether system failure lies in signal source (design deficiency), decoder (user expectation mismatch), or interface mapping (perceptual misalignment). This framework transforms abstract motivational theories into operationalizable design guidance by characterizing the objective signal space within which psychological mechanisms operate.",
            JA: "インタラクティブシステムにおける参加行動は、通常、デザイン特徴または心理状態のいずれかを通じて分析されますが、客観的なメカニズムと主観的な体験の間には説明のギャップが存在します。本研究では、設計属性（信号源）とエージェントの知覚（デコーダー）を分離する二層診断アーキテクチャを通じて、このギャップを埋めるデザイン理論的分類法（タクソノミー）を開発しました。参加性向を、アウトプット、コスト、時間、動機、失敗コスト、リスク構造からなる7次元の直交ベクトル空間として定義し、14,717件のレビューを用いた検証により、その直交性、最小完備性、および行動的妥当性を証明しました。このフレームワークにより、エンゲージメントの失敗原因が設計上の欠陥（信号源）、期待の不一致（デコーダー）、または認識の不整合（マッピング）のどこにあるかを正確に診断することが可能になります。"
        },
        category: 'Paper',
        paperType: 'Full Paper',
        originalLangs: { CN: "英文", EN: "English", JA: "英語" },
        lengths: { CN: "33页", EN: "33 Pages", JA: "33ページ" },
        isInternal: false,
        journal: 'TOCHI (Desk Review)',
        publisher: 'ACM',
        impactFactor: '0',
        preprintUrl: 'https://doi.org/10.36227/techrxiv.177203276.63908007/v1',
        externalUrl: ''
    },
    {
        id: 'participation-utility-model',
        titles: {
            CN: "解构参与感：不确定性下参与倾向的设计理论框架",
            EN: "Deconstructing Engagement: A Design-Theoretic Framework for Participation Propensity under Uncertainty",
            JA: "エンゲージメントの解構：不確実性下における参加性向のためのデザイン理論的枠組み"
        },
        date: '2026.02.01',
        descriptions: {
            CN: "游戏分析通过行为指标和数据驱动的优化，在理解玩家行为方面建立了强大的方法。然而，要全面解释为什么某些结构配置会产生观察到的行为模式，分析需要一个补充性的定性层面——解释数据背后因果机制的结构性背景。本文提出了一个设计理论审计框架，用于分析交互系统中的参与倾向。该框架将参与视为一种心理状态，更将其表征为短期参与度与长期价值追求之间的张力，并受“价值范畴（Value Scope）”的调节。本研究将决策空间分解为结果收益、总成本、时间投入、动机、失败成本和风险等七个维度，旨在为诊断导致参与失效的结构性原因提供分析视角，而非单纯依赖经验性的留存调优。",
            EN: "Game analytics has established powerful methods for understanding what happens in player behavior through behavioral metrics and data-driven optimization [7]. However, to fully interpret why certain structural configurations produce observed behavioral patterns, analytics requires a complementary qualitative layer—a structural context that explains the causal mechanisms behind the data. This paper proposes a design-theoretic auditing framework for analyzing participation propensity in interactive systems. Rather than modeling engagement as a monolithic psychological state, participation is characterized as a tension between short-term engagement propensity and long-term value pursuit, moderated by the system’s Value Scope (SV), which reflects the transferability of outcomes beyond the system boundary. The framework decomposes the participation decision space into seven analytically separable dimensions, including Outcome Payoff, Total Cost, Temporal Commitment, Motivation, Failure Cost, and Risk. This decomposition is not claimed to be formally minimal or predictive, but is constructed to support structured design auditing by distinguishing often-conflated mechanisms such as sunk cost versus failure cost, and by introducing risk entanglement as a systemic amplification factor in multi-agent settings. By framing participation as a rational auditing process rather than a purely experiential response, this work aims to provide designers and researchers with an analytical lens for diagnosing structural causes of engagement failure beyond empirical retention tuning. ",
            JA: "ゲーム分析は、行動指標とデータ駆動の最適化を通じて、プレイヤーの行動に何が起こるかを理解するための強力な手法を確立している[7]。しかし、特定の構造構成が観察された行動パターンを生成する理由を完全に解釈するためには、分析には補完的な定性層、すなわちデータの背后にある因果メカニズムを説明する構造的文脈が必要である。本稿では、インタラクティブシステムにおける参加性向を分析するためのデザイン理論的監査フレームワークを提案する。エンゲージメントを単一の心理状態としてモデル化するのではなく、参加を短期的関与と長期的価値追求の間の緊張関係として特徴づけ、システムの価値スコープ（SV）によって調整されるものとする。このフレームワークは、決定空間を7つの分析的に分離可能な次元に分解し、結果のペイオフ、总コスト、时间的コミットメント、动机、失败コスト、リスクなどを含む。この分解は形式的に最小または予測的であると主張するものではないが、埋没コストと失败コストなど、しばしば混同されるメカニズムを区別し、マルチエージェント設定における体系的な增幅因子としてリスクの络み合いを导入することによって、构造化されたデザイン監査をサポートするように构成されている。参加を純粋に経験的な応答としてではなく、合理的な監査プロセスとして捉えることにより、本研究は、経験的なリテンションチューニングを超えて、エンゲージメント失败の构造的原因を诊断するための分析的レンズをデザイナーや研究者に提供することを目指している。"
        },
        category: 'Paper',
        paperType: 'Full Paper',
        originalLangs: { CN: "英文", EN: "English", JA: "英語" },
        lengths: { CN: "8页", EN: "8 Pages", JA: "8ページ" },
        isInternal: false,
        journal: 'IEEE ToG (Peer Review)',
        publisher: 'IEEE',
        impactFactor: '0',
        preprintUrl: 'https://doi.org/10.36227/techrxiv.177212584.42401805/v1',
        externalUrl: ''
    },
    {
        id: 'ffxiv-exploration-value-collapse',
        titles: {
            CN: "选择的错觉：MMORPG探索内容在奖励解耦后的价值崩塌",
            EN: "The Illusion of Choice: Value Collapse in MMORPG Exploratory Content Post-Reward Decoupling",
            JA: "選択の錯覚：報酬の切り離し後におけるMMORPG探索コンテンツの価値崩壊"
        },
        date: '2026.01.25',
        descriptions: {
            CN: "过去十年间，《最终幻想14》的大型探索内容经历了从\"强制垄断\"到\"完全解耦\"的范式转变。本文运用理性选择理论，分析了四个不同时期的玩家留存情况：云冠群岛、禁地优雷卡、博兹雅，以及近期的奥秘暗域。通过建立探索效用方程，我分离出三个关键变量：排他性溢价(α)、环境摩擦(F)和认知负荷(C)。研究发现，在存在高收益外部替代选项的情况下，排他性溢价似乎是主导性解释因素。我将云冠群岛定性为系统性失败，禁地优雷卡定性为由\"垄断红利\"驱动的成功案例，而博兹雅/奥秘暗域则因奖励解耦而沦为\"价值崩塌\"的受害者。社区普查数据表明，奥秘暗域呈现出约90%的极端脱离倾向，这表明在高认知负荷与零奖励排他性叠加条件下的理性市场反应。我的结论是，观察到的资源错配源于效用变量的结构性失调——具体表现为排他性(α)降低后，未能相应降低认知负荷(C)及其他系统参数。",
            EN: "Over the past decade, Final Fantasy XIV\'s large-scale exploratory content has undergone a paradigm shift from \"Coercive Monopoly\" to \"Complete Decoupling.\" This paper applies Rational Choice Theory to analyze player retention across four distinct eras: The Diadem, Eureka, Bozja, and the recent Occult Crescent. By establishing an Exploration Utility Equation, I isolate three critical variables: Exclusivity Premium (α), Environmental Friction (F), and Cognitive Load (C). My findings indicate that the Exclusivity Premium appears to be the dominant explanatory factor in the presence of high-yield external alternatives. I identify The Diadem as a systemic failure, Eureka as a success driven by \"Monopoly Dividend,\" and Bozja/Occult Crescent as victims of \"Value Collapse\" due to Reward Decoupling. Community census data suggests that Occult Crescent exhibits an extreme disengagement tendency of estimated 90%, indicating a rational market response to high Cognitive Load combined with zero reward exclusivity. I conclude that the observed resource misallocation stems from a structural misalignment of utility variables—specifically, the reduction of Exclusivity (α) without a compensatory reduction in Cognitive Load (C) and other systemic parameters.",
            JA: "過去10年間、『ファイナルファンタジーXIV』の大規模探索コンテンツは、「強制的独占」から「完全な切り離し」へとパラダイムシフトを遂げた。本稿では合理的選択理論を用い、4つの異なる時期（ディアデム諸島、禁断の地 エウレカ、ボズヤ、そして最近のオルト・エウレカ）におけるプレイヤーの継続率を分析する。探索効用方程式を構築することで、独占プレミアム(α)、環境の摩擦(F)、認知負荷(C)という3つの重要な変数を分離した。その結果、高利回りの外部代替選択肢が存在する場合、独占プレミアムが支配的な説明要因であることが示唆された。ディアデム諸島をシステム的な失敗、エウレカを「独占の配当」による成功例、 seniorそしてボズヤ/オルト・エウレカを報酬の切り離しによる「価値崩壊」の犠牲者として定義する。コミュニティの調査データによると、オルト・エウレカは約90%という極端な離脱傾向を示しており、これは高い認知負荷とゼロの報酬独占性が重なった条件下の合理的な市場反応である。結論として、観察された資源のミスマッチは効用変数の構造的な不適合、具体的には独占性(α)の低下に対応した認知負荷(C)や他系统パラメータの低减が行われなかったことに起因すると考える。"
        },
        category: 'Paper',
        paperType: 'Letter',
        originalLangs: { CN: "英文", EN: "English", JA: "英語" },
        lengths: { CN: "4页", EN: "4 Pages", JA: "4ページ" },
        isInternal: false,
        journal: 'IEEE ToG (Peer Review)',
        publisher: 'IEEE',
        impactFactor: '0',
        preprintUrl: 'https://doi.org/10.36227/techrxiv.177091887.71276991/v1',
        externalUrl: ''
    },
    // ─── Test Lecture Entry ───
    // {
    //     id: 'test-conference-talk',
    //     titles: {
    //         CN: "参与式系统设计：从理论到量化审计",
    //         EN: "Participatory System Design: From Theory to Quantitative Auditing",
    //         JA: "参加型システム設計：理論から定量的監査へ"
    //     },
    //     date: '2026.03',
    //     descriptions: {
    //         CN: "探讨如何将参与式设计理论转化为可量化、可审计的设计诊断工具，通过双层架构将系统属性与用户感知分离，实现结构化的体验评估。",
    //         EN: "Exploring how to transform participatory design theory into quantifiable, auditable design diagnostic tools through a dual-layer architecture that separates system properties from user perception.",
    //         JA: "参加型デザイン理論を、システム属性とユーザー認知を分離する二層アーキテクチャにより定量的かつ監査可能なデザイン診断ツールへと変換する方法を探求する。"
    //     },
    //     category: 'Lecture',
    //     lectureType: 'Conference',
    //     venue: 'Games for Change (G4C)',
    //     duration: '45 min',
    //     deckUrl: 'https://example.com/deck',
    //     originalLangs: { CN: "英文", EN: "English", JA: "英語" },
    //     lengths: { CN: "45分钟", EN: "45 min", JA: "45分" },
    //     isInternal: false,
    //     journal: '',
    //     publisher: 'GDC',
    //     impactFactor: '0',
    //     preprintUrl: '',
    //     externalUrl: 'https://example.com/talk'
    // },
    // --- GDDs: Test Papers (策划测试题) ---
    {
        id: 'ff14-frontline',
        titles: { CN: "FFXIV战场系统设计提案", EN: "FFXIV Frontline System Design Proposal", JA: "FFXIVフロントライン 系统设计提案书" },
        date: '2024.03',
        descriptions: {
            CN: "申请SE第三工作室系统策划岗位（PVP方向）时撰写的测试题。针对《最终幻想14》现有战场（Frontline）玩法进行深度分析，并提出新规则与系统优化方案。",
            EN: "A test assignment written when applying for the System Planner position (PVP direction) at Square Enix Creative Business Unit III. Features in-depth analysis of FFXIV\'s existing Frontline PVP mode with proposed new rules and system improvements.",
            JA: "スクウェア・エニックス第三開発事業本部（CBU III）のシステムプランナー（PVP担当）に応募した際に作成した課題。FFXIVの既存のフロントライン（PVP）を深く分析し、新ルールとシステムの最適化案を提案したもの。"
        },
        url: '/assets/docs/FF14FrontlineDesign.pdf',
        category: 'GDD',
        gddType: 'Test',
        originalLangs: { CN: "日文", EN: "Japanese", JA: "日本語" },
        lengths: { CN: "44页", EN: "44 Pages", JA: "44ページ" },
        isInternal: false,
        publisher: 'None',
        targetPositions: { CN: "SE第三工作室 系统策划 (PVP向)", EN: "SE CBU III System Planner (PVP)", JA: "スクエニ 第三開発事業本部 システムプランナー (PVP担当)" }
    },
    {
        id: 'ugc-gameplay-test',
        titles: { CN: "UGC玩法策划测试题", EN: "UGC Gameplay Planner Test", JA: "UGCゲームプレイプランナー 試験課題" },
        date: '2026.01',
        descriptions: {
            CN: "申请UGC玩法策划岗位时完成的设计测试题，涉及用户生成内容的系统设计与玩法创新。",
            EN: "A design test completed when applying for a UGC Gameplay Planner position, covering user-generated content system design and gameplay innovation.",
            JA: "UGCゲームプレイプランナー職への応募時に完成させた設計テスト。ユーザー生成コンテンツ（UGC）のシステム設計とゲームプレイの革新に関する内容。"
        },
        url: '/assets/docs/Test1.pdf',
        category: 'GDD',
        gddType: 'Test',
        originalLangs: { CN: "中文", EN: "Chinese", JA: "中国語" },
        lengths: { CN: "38页", EN: "38 Pages", JA: "38ページ" },
        isInternal: false,
        publisher: 'None',
        targetPositions: { CN: "UGC玩法策划", EN: "UGC Gameplay Planner", JA: "UGCゲームプレイプランナー" }
    },
    {
        id: 'quest-design-test',
        titles: { CN: "任务策划测试题", EN: "Quest Design Test", JA: "クエストプランナー 試験課題" },
        date: '2024.06',
        descriptions: {
            CN: "求职过程中撰写的任务策划岗位测试题，展示任务系统设计与叙事整合能力。",
            EN: "A quest design test written during job application, demonstrating quest system design and narrative integration capabilities.",
            JA: "就職活動中に作成したクエストプランナー職の試験課題。クエストシステムの設計とナラティブの統合能力を提示。"
        },
        url: '/assets/docs/Test3.pdf',
        category: 'GDD',
        gddType: 'Test',
        originalLangs: { CN: "中文", EN: "Chinese", JA: "中国語" },
        lengths: { CN: "6页", EN: "6 Pages", JA: "6页" },
        isInternal: false,
        publisher: 'None',
        targetPositions: { CN: "任务策划", EN: "Quest Designer", JA: "クエストプランナー" }
    },
    {
        id: 'pre-research-test',
        titles: { CN: "预研项目笔试题", EN: "Pre-Research Project Test", JA: "先行研究プロジェクト 笔记入试课题" },
        date: '2025.11',
        descriptions: {
            CN: "针对创意型预研项目岗位撰写的攻坚型笔试题，展示从零到一的创意设计能力、系统架构思维以及创新性玩法探索。内容涵盖项目定位、核心玩法设计、系统拆解与技术预研等多个维度。",
            EN: "A challenging written test for a creative pre-research project position, demonstrating ability to design from zero to one, system architecture thinking, and innovative gameplay exploration. Covers project positioning, core gameplay design, system breakdown, and technical pre-research.",
            JA: "クリエイティブな先行研究プロジェクト職向けの高度な筆記課題。ゼロからイチへのクリエイティブ力、システムアーキテクチャ思考、革新的なゲームプレイ探索を提示。プロジェクトのポジショニング、コアプレイ設計、システム分解、技術的予察など多角的な内容。"
        },
        url: '/assets/docs/Test4.pdf',
        category: 'GDD',
        gddType: 'Test',
        originalLangs: { CN: "中文", EN: "Chinese", JA: "中国語" },
        lengths: { CN: "36页", EN: "36 Pages", JA: "36ページ" },
        isInternal: false,
        publisher: 'None',
        targetPositions: { CN: "预研项目策划", EN: "Pre-Research Project Designer", JA: "先行研究プロジェクトプランナー" }
    },

    // --- GDDs: Analysis (分析研究) ---
    {
        id: 'exploration-design',
        titles: {
            CN: "FFXIV特殊场景探索玩法设计分析",
            EN: "FFXIV Special Zone Exploration Design Analysis",
            JA: "FFXIV 特殊フィールド探索コンテンツ 设计分析"
        },
        date: '2024.03',
        descriptions: {
            CN: "2023年完成、2024年公开的极度详细的《最终幻想14》特殊场景探索玩法设计分析。深入探讨禁地优雷卡、博兹雅等大型探索内容的设计理念、系统架构与玩家体验，涵盖场景交互设计、动态事件系统、长线留存机制等核心议题。",
            EN: "An extremely detailed analysis of FFXIV special zone exploration gameplay design, completed in 2023 and published in 2024. Deep-dives into the design philosophy, system architecture, and player experience of large-scale exploratory content like Eureka and Bozja, covering scene interaction design, dynamic event systems, and long-term retention mechanisms.",
            JA: "2023年に作成、2024年に公開された『ファイナルファンタジーXIV』の特殊フィールド探索コンテンツに関する極めて詳細な設計分析。エウレカやボズヤなどの大規模探索コンテンツの設計理念、システムアーキテクチャ、プレイヤー体験を深く掘り下げ、フィールド内のインタラクション設計、ダイナミックイベントシステム、長期継続メカニズムなどの核心的なトピックを網羅。"
        },
        url: '/assets/docs/SpecialExplorationDesign.pdf',
        category: 'GDD',
        gddType: 'Analysis',
        originalLangs: { CN: "中文", EN: "Chinese", JA: "中国語" },
        lengths: { CN: "28页", EN: "28 Pages", JA: "28ページ" },
        publisher: 'None',
        isInternal: false
    },
    {
        id: 'tech-due-diligence-audit',
        titles: {
            CN: "技术尽职调查与工程审计报告",
            EN: "Technical Due Diligence & Engineering Audit Report",
            JA: "技術デューデリジェンス＆エンジニアリング監査報告書"
        },
        date: '2026.01',
        descriptions: {
            CN: "针对某游戏项目的全面技术审计报告（脱敏版）。审计范围涵盖源代码仓库、工程基础设施、C++ 实现细节、开发工作流以及数字资产安全性。识别了版本控制完整性、持续集成可靠性、架构模块化等方面的关键风险，并提供了分阶段整改建议。",
            EN: "A comprehensive technical audit report for a game project (redacted version). The audit scope covers source code repositories, engineering infrastructure, C++ implementation details, development workflows, and digital asset security. Identifies critical risks in version control integrity, CI reliability, and architectural modularity, with phased remediation recommendations.",
            JA: "あるゲームプロジェクトに対する包括的な技術監査報告書（匿名化版）。監査範囲はソースコードリポジトリ、エンジニアリングインフラ、C++実装詳細、開発ワークフロー、デジタル資産のセキュリティを網羅。バージョン管理の完全性、CI信頼性、アーキテクチャのモジュール化における重要なリスクを特定し、段階的な改善提案を提示。"
        },
        url: '/assets/docs/audit.html',
        category: 'GDD',
        gddType: 'Analysis',
        originalLangs: { CN: "中文", EN: "Chinese", JA: "中国語" },
        lengths: { CN: "1页 (HTML)", EN: "1 Page (HTML)", JA: "1ページ (HTML)" },
        publisher: 'None',
        isInternal: false
    },

    // --- GDDs: Methodology (方法论/教程) ---
    {
        id: 'emotional-design-method',
        titles: { CN: "游戏情感设计方法论", EN: "Game Emotional Design Methodology", JA: "ゲーム感情設計メソッド" },
        date: '2025.09',
        descriptions: {
            CN: "一套旨在提高设计下限而非提升上限的游戏情感设计方法论。视角极高，颗粒度极粗，作用是让没有设计基础的人快速建立情感设计框架，提高设计下限。注意：本文对上限提高、情感投放逻辑、频率控制、认知负荷等进阶话题基本没有提及。",
            EN: "A game emotional design methodology aimed at raising the design floor rather than the ceiling. High-level perspective with coarse granularity, designed to help people without design fundamentals quickly establish an emotional design framework. Note: This document does not cover advanced topics such as raising the ceiling, emotional delivery logic, frequency control, or cognitive load.",
            JA: "デザインの上限を上げるのではなく、下限を底上げすることを目的としたゲーム感情設計メソッド。極めて高い視点と粗い粒度で構成され、デザインの基礎がない人でも迅速に感情設計の枠組みを構築できるようにするもの。注：本稿では、上限の向上、感情投入のロジック、頻度制御、認知負荷などの高度な話題には触れていない。"
        },
        url: '/assets/docs/Method1.pdf',
        category: 'GDD',
        gddType: 'Methodology',
        originalLangs: { CN: "中文", EN: "Chinese", JA: "中国语" },
        lengths: { CN: "47页", EN: "47 Pages", JA: "47ページ" },
        publisher: 'None',
        isInternal: true
    },
    {
        id: 'professional-communication',
        titles: { CN: "策划专业度提升指南：认知纠偏与沟通技巧", EN: "Professional Communication Guide for Game Designers", JA: "ゲームプランナーのためのプロフェッショナル・コミュニケーションガイド" },
        date: '2025.11',
        descriptions: {
            CN: "针对游戏策划行业的认知纠偏教程，帮助从业者建立正确的设计思维并提高与他人（包括程序、美术、制作人等）沟通时的专业度。适合希望提升职业素养与跨部门协作能力的策划人员。",
            EN: "A tutorial on cognitive correction for the game design industry, helping practitioners establish correct design thinking and improve professionalism when communicating with others (including programmers, artists, producers, etc.). Suitable for planners looking to enhance professional quality and cross-department collaboration skills.",
            JA: "ゲーム業界向けの認知バイアス修正チュートリアル。設計思考を正し、他職種（プログラマー、アーティスト、プロデューサーなど）とのコミュニケーションにおけるプロフェッショナル度を高める。職業的素養と部門間協力能力を向上させたいプランナーに最適。"
        },
        url: '/assets/docs/Method2.pdf',
        category: 'GDD',
        gddType: 'Methodology',
        originalLangs: { CN: "中文", EN: "Chinese", JA: "中国語" },
        lengths: { CN: "8页", EN: "8 Pages", JA: "8ページ" },
        publisher: 'None',
        isInternal: true
    },

    // --- GDDs: Full GDD ---
    {
        id: 'mountain-sea-gdd',
        titles: { CN: "山海 - 游戏设计文档", EN: "The Mountain Sea - GDD", JA: "山海 - ゲーム设计文书" },
        date: '2023.10',
        descriptions: {
            CN: "2D动作平台游戏的完整策划文档，包含系统拆解与关卡规划。",
            EN: "Complete GDD for a 2D action platformer, including system and level planning.",
            JA: "2Dアクションプラットフォーマーの完全な仕様書。システム分解とレベルプランニングを含む。"
        },
        url: '/assets/docs/TheMountainSeaGDD.pdf',
        category: 'GDD',
        gddType: 'GDD',
        originalLangs: { CN: "中文", EN: "Chinese", JA: "中国语" },
        lengths: { CN: "17页", EN: "17 Pages", JA: "17ページ" },
        publisher: 'None',
        isInternal: false
    }
];